### PR TITLE
Add gitkraken evolottery

### PR DESCRIPTION
**Pull request by bobturneruk**

### CODE REVIEW

**Comment by bobturneruk** [comment]
resolves #1

**Review by annakrystalli — APPROVED** [review]

**Comment by annakrystalli** [comment]
Looks good to me

**Comment by bobturneruk** [comment]
Do you think the first two pages should be a separate introduction delivered prior to the breakouts, to avoid replication?

**Comment by bobturneruk** [comment]
(And also you'll do a better job of introducing it to everyone than me or @davidwilby!)

**Comment by annakrystalli** [comment]
Maybe but let's just merge this in for now

**Pull request merged**
